;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		backward-sexp
		counsel-M-x
		forward-sexp
		iflipb-next-buffer
		ivy-switch-buffer
		keyboard-escape-quit
		mozc-handle-event
		org-beginning-of-line
		org-cycle
		org-delete-char
		org-end-of-line
		org-forward-sentence
		org-kill-line
		org-return
		org-return-and-maybe-indent
		org-self-insert-command
		org-yank
		other-window-or-split
		toggle-input-method
		))

(setq mc/cmds-to-run-once
      '(
		counsel-find-file
		elscreen-toggle
		kmacro-end-or-call-macro
		rectangle-mark-mode
		yank-rectangle
		))
